services:
  user-management:
    image: sanah22/user-management-service:0.1.0
    container_name: user_mgmt_app
    depends_on:
      db:
        condition: service_healthy
      notification-service:
        condition: service_started

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${UM_MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

      APP_JWT_SECRET: ${APP_JWT_SECRET}
      APP_JWT_EXPIRY_MINUTES: ${APP_JWT_EXPIRY_MINUTES}

      NOTIFICATION_SERVICE_BASE_URL: http://notification-service:8082
    ports:
      - "${APP_PORT}:8080"

  notification-service:
    image: sanah22/notification-service:0.1.0
    container_name: notification-service
    depends_on:
      - kafka
      - redis
      - mailhog
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_MAIL_HOST: mailhog
      SPRING_MAIL_PORT: 1025
    ports:
      - "8082:8082"

  bulk_orch_app:
    image: sanah22/bulk-orchestration:latest
    container_name: bulk_orch_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${BO_MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      USER_MANAGEMENT_BASE_URL: http://user-management:8080
    ports:
      - "8083:8083"

  db:
    image: mysql:8.0
    container_name: user_mgmt_db
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: "%"
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - user_mgmt_db_data:/var/lib/mysql
      - ./db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
    command: [
      "--default-authentication-plugin=mysql_native_password",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci"
    ]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

  kafka:
    image: bitnamilegacy/kafka:4.0.0-debian-12-r10
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - ALLOW_PLAINTEXT_LISTENER=yes

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  user_mgmt_db_data:
